version: "3.7"

services:
  source-finder-db:
    image: postgres

  source-finder-python:
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - DATABASE_HOST=source-finder-db
    volumes:
      - .:/code
    depends_on:
      - source-finder-db
