# Generated by Django 3.0.3 on 2020-02-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrueSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.FloatField()),
                ("ra_core", models.CharField(max_length=255)),
                ("dec_core", models.CharField(max_length=255)),
                ("ra_centroid", models.CharField(max_length=255)),
                ("dec_centroid", models.CharField(max_length=255)),
                ("flux", models.FloatField()),
                ("core_fraction", models.FloatField()),
                ("bmaj", models.FloatField()),
                ("bmin", models.FloatField()),
                ("position_angle", models.FloatField()),
                ("size", models.FloatField()),
                ("classification", models.CharField(max_length=255)),
                ("selection", models.BooleanField()),
                ("x_centroid", models.FloatField()),
                ("y_centroid", models.FloatField()),
            ],
        )
    ]
